version: '3.9'

services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
